import type { AddonMetadata } from "@components/Wintry/Settings/pages/Addon";
import type { WintryTheme } from "../types";

export const EYE_CANDY_THEME: WintryTheme = {
    id: "eye.candy",
    type: "theme",
    display: {
        name: "Eye Candy",
        description: "Lumi port of Hanibee's Eye Candy theme",
        authors: [
            {
                name: "Mudaranrhiod",
                id: "807170846497570848",
            },
        ],
    },
    main: {
        base: "dark",
        colors: {
            semantic: {
                ANDROID_RIPPLE: {
                    value: "#CFC7D8",
                    opacity: 0.24,
                },
                BACKGROUND_ACCENT: { value: "#C88EAD" },
                BACKGROUND_MENTIONED: {
                    value: "#BDBAEB",
                    opacity: 0.09,
                },
                BACKGROUND_MENTIONED_HOVER: {
                    value: "#101320",
                    opacity: 0.20,
                },
                BACKGROUND_MOBILE_PRIMARY: { value: "#3F3E4A" },
                BACKGROUND_MOBILE_SECONDARY: { value: "#61606D" },
                BACKGROUND_MODIFIER_ACCENT: { value: "#5A5966" },
                BACKGROUND_MODIFIER_ACTIVE: { value: "#5A5966" },
                BACKGROUND_MODIFIER_HOVER: {
                    value: "#101320",
                    opacity: 0.20,
                },
                BACKGROUND_MODIFIER_SELECTED: { value: "#585666" },
                BACKGROUND_PRIMARY: { value: "#4B4957" },
                BACKGROUND_SECONDARY: { value: "#3F3E4A" },
                BACKGROUND_SECONDARY_ALT: { value: "#5A4D5E" },
                BACKGROUND_TERTIARY: { value: "#5A4D5E" },
                BACKGROUND_MESSAGE_HOVER: {
                    value: "#101320",
                    opacity: 0.20,
                },
                BG_BASE_PRIMARY: { value: "#4B4957" },
                BG_BASE_SECONDARY: { value: "#3F3E4A" },
                BG_BASE_TERTIARY: { value: "#484654" },
                BG_MOD_SUBTLE: {
                    value: "#C4967A",
                    opacity: 0.24,
                },
                BG_BRAND: { value: "#C3A16E" },
                BG_SURFACE_RAISED: { value: "#4B4957" },
                BG_SURFACE_OVERLAY_TMP: { value: "#474655" },
                BORDER_FAINT: { value: "#696779" },
                CARD_PRIMARY_BG: { value: "#4B4957" },
                CARD_SECONDARY_BG: { value: "#474453" },
                CHANNEL_ICON: { value: "#BDBECC" },
                CHANNELS_DEFAULT: { value: "#E8E8EA" },
                EMBED_BACKGROUND: { value: "#3F3E4A" },
                HEADER_PRIMARY: { value: "#FFF" },
                HEADER_SECONDARY: { value: "#BDBECC" },
                INPUT_PLACEHOLDER_TEXT: { value: "#CEB0CD" },
                INTERACTIVE_ACTIVE: { value: "#FFF" },
                INTERACTIVE_HOVER: {
                    value: "#101320",
                    opacity: 0.20,
                },
                INTERACTIVE_MUTED: { value: "#696779" },
                INTERACTIVE_NORMAL: { value: "#BDBECC" },
                MENTION_BACKGROUND: {
                    value: "#DFBE80",
                    opacity: 0.30,
                },
                MENTION_FOREGROUND: { value: "#89b4fa" },
                POLLS_VICTOR_FILL: {
                    value: "#D1B681",
                    opacity: 0.20,
                },
                REDESIGN_ACTIVITY_CARD_BACKGROUND: { value: "#474453" },
                REDESIGN_BUTTON_PRIMARY_BACKGROUND: { value: "#C3A16E" },
                REDESIGN_BUTTON_PRIMARY_PRESSED_BACKGROUND: { value: "#b48a4a" },
                REDESIGN_BUTTON_SECONDARY_BACKGROUND: { value: "#5A5966" },
                REDESIGN_BUTTON_SECONDARY_PRESSED_BACKGROUND: { value: "#42414b" },
                REDESIGN_BUTTON_SECONDARY_OVERLAY_BACKGROUND: { value: "#5A4D5E8a" },
                REDESIGN_BUTTON_SECONDARY_OVERLAY_PRESSED_BACKGROUND: { value: "#5A4D5E" },
                REDESIGN_BUTTON_SECONDARY_BORDER: { value: "#696779" },
                REDESIGN_BUTTON_TERTIARY_BACKGROUND: { value: "#5A4D5E" },
                REDESIGN_BUTTON_TERTIARY_PRESSED_BACKGROUND: { value: "#3f3642" },
                REDESIGN_CHANNEL_CATEGORY_NAME_TEXT: { value: "#E8E8EA" },
                REDESIGN_CHANNEL_NAME_TEXT: { value: "#ffffff" },
                REDESIGN_CHAT_INPUT_BACKGROUND: { value: "#5A4D5E" },
                REDESIGN_INPUT_CONTROL_ACTIVE_BG: { value: "#B17B93" },
                REDESIGN_INPUT_CONTROL_SELECTED: { value: "#C2A775" },
                STATUS_DND: { value: "#C4967A" },
                STATUS_DANGER: { value: "#C4967A" },
                STATUS_POSITIVE: { value: "#D1B681" },
                TEXT_DANGER: { value: "#C4967A" },
                TEXT_LINK: { value: "#FFE1C1" },
                TEXT_MUTED: { value: "#CEB0CD" },
                TEXT_NORMAL: { value: "#E8E8EA" },
                TEXT_PRIMARY: { value: "#E8E8EA" },
                THREAD_CHANNEL_SPINE: { value: "#C88EAD" }
            },
            raw: {
                BLUE_330: "#FFE1C1",
                BLUE_345: "#FFE1C1",
                BRAND_230: "#D0B278",
                BRAND_260: "#AF986B",
                BRAND_300: "#C3A16E",
                BRAND_360: "#E8E8EA",
                BRAND_500: "#C88EAD",
                BRAND_560: "#C88EAD",
                BRAND_730: "#9F8657",
                BRAND_NEW_500_ALPHA_20: "#C88EAD",
                CHAT_MENTIONS_BACKGROUND_DARK: "#DFBE804D",
                CHAT_MENTIONS_FOREGROUND_DARK: "#DFBE80",
                GREEN_100: "#D1B681",
                GREEN_130: "#D1B681",
                GREEN_160: "#D1B681",
                GREEN_200: "#D1B681",
                GREEN_230: "#D1B681",
                GREEN_260: "#D1B681",
                GREEN_300: "#D1B681",
                GREEN_330: "#D1B681",
                GREEN_345: "#D1B681",
                GREEN_360: "#90B27C",
                GREEN_400: "#D1B681",
                GREEN_430: "#D1B681",
                GREEN_460: "#c3a15c",
                GREEN_500: "#D1B681",
                GREEN_530: "#D1B681",
                GREEN_560: "#D1B681",
                GREEN_600: "#D1B681",
                GREEN_630: "#D1B681",
                GREEN_660: "#D1B681",
                GREEN_700: "#D1B681",
                GREEN_730: "#D1B681",
                GREEN_760: "#D1B681",
                GREEN_800: "#D1B681",
                GREEN_830: "#D1B681",
                GREEN_860: "#D1B681",
                GREEN_900: "#D1B681",
                GUILD_BOOSTING_BLUE: "#AF986B",
                GUILD_BOOSTING_BLUE_FOR_GRADIENTS: "#AF986B",
                GUILD_BOOSTING_PINK: "#BF91A8",
                GUILD_BOOSTING_PURPLE: "#BF91A8",
                GUILD_BOOSTING_PURPLE_FOR_GRADIENTS: "#8F669C",
                ORANGE_345: "#B2814D",
                PLUM_9: "#BDBECC",
                PLUM_10: "#8E9297",
                PLUM_11: "#696779",
                PLUM_13: "#5A4D5E",
                PLUM_15: "#75748B",
                PLUM_16: "#C88EAD",
                PLUM_17: "#5A4D5E",
                PLUM_18: "#3F3E4A",
                PLUM_19: "#5A4D5E",
                PLUM_20: "#3F3E4A",
                PLUM_22: "#484654",
                PLUM_24: "#5A4D5E",
                PLUM_3: "#E8E8EA",
                PLUM_6: "#E8E8EA",
                PREMIUM_PERK_PINK: "#C88EAD",
                PREMIUM_PERK_PURPLE: "#7D2D59",
                PREMIUM_TIER_0_HEADER_GRADIENT_1: "#EEB1CA",
                PREMIUM_TIER_0_HEADER_GRADIENT_2: "#DCB975",
                PREMIUM_TIER_0_HEADER_GRADIENT_3: "#DCB975",
                PREMIUM_TIER_0_HEADER_GRADIENT_4: "#EEB1CA",
                PREMIUM_TIER_0_HEADER_GRADIENT_5: "#EEB1CA",
                PREMIUM_TIER_2_PINK_FOR_GRADIENTS: "#BF91A8",
                PREMIUM_TIER_2_PURPLE_FOR_GRADIENTS: "#BF91A8",
                PREMIUM_TIER_2_PURPLE_FOR_GRADIENTS_2: "#AF986B",
                PRIMARY_100: "#EAEAEE",
                PRIMARY_200: "#E8E8EA",
                PRIMARY_330: "#fffeff",
                PRIMARY_360: "#FEF0F8",
                PRIMARY_400: "#CE7DA0",
                PRIMARY_460: "#4B4957",
                PRIMARY_500: "#8F669C",
                PRIMARY_530: "#D1B681",
                PRIMARY_600: "#3F3E4A",
                PRIMARY_630: "#474453",
                PRIMARY_645: "#EAA3C5",
                PRIMARY_660: "#3F3E4A",
                PRIMARY_700: "#3F3E4A",
                PRIMARY_730: "#3F3E4A",
                PRIMARY_800: "#61606D",
                RED_260: "#C4967A",
                RED_300: "#C4967A",
                RED_330: "#C4967A",
                RED_345: "#C4967A",
                RED_360: "#C4967A",
                RED_400: "#C5A361",
                RED_430: "#C4967A",
                RED_460: "#b47b57",
                RED_500: "#C4967A",
                RED_530: "#C4967A",
                RED_560: "#C4967A",
                RED_600: "#C4967A",
                RED_630: "#C4967A",
                RED_660: "#C4967A",
                RED_700: "#C4967A",
                WHITE_500: "#FFFFFF",
                WHITE_630: "#696779",
                YELLOW_100: "#D0B278",
                YELLOW_130: "#D0B278",
                YELLOW_160: "#D0B278",
                YELLOW_200: "#D0B278",
                YELLOW_230: "#D0B278",
                YELLOW_260: "#D0B278",
                YELLOW_300: "#C3A260",
                YELLOW_330: "#D0B278",
                YELLOW_345: "#D0B278",
                YELLOW_360: "#D0B278",
                YELLOW_400: "#D0B278",
                YELLOW_430: "#D0B278",
                YELLOW_460: "#D0B278",
                YELLOW_500: "#D0B278",
                YELLOW_530: "#D0B278",
                YELLOW_560: "#D0B278",
                YELLOW_600: "#D0B278",
                YELLOW_630: "#D0B278",
                YELLOW_660: "#D0B278",
                YELLOW_700: "#D0B278",
                YELLOW_730: "#D0B278",
                YELLOW_760: "#D0B278",
                YELLOW_800: "#D0B278",
                YELLOW_830: "#D0B278",
                YELLOW_860: "#D0B278",
                YELLOW_900: "#D0B278"

            },
        },
    },
    asAddonMetadata(): AddonMetadata {
        throw new Error("Function not implemented.");
    },
};
